### ISSUE TITLE
!IMPORTANT! Nbr d'heure de la semaine

### ISSUE THREAD

**Issue by hugoschellinger** [MrWarzo/Enhanced-CKT-Dashboard#2]
- Nombre d'heure par jour de la semaine
- Ecart-type de la moyenne d'heure des jours de la semaine sur chaque mois de l'année

**Comment by MrWarzo** [comment]
Ca reprend cet issue #1 
Je ferme celle la pour éviter la duppli

**Comment by hugoschellinger** [comment]
nan laisse ouvert

**Comment by hugoschellinger** [comment]
Ou conséquence
